export const dummyStats = [
    {
        id: 'stat-mic',
        icon: 'icon-microphone',
        hidden: false,
        color: '#ede100',
        value: 33,
        min: 0,
        max: 100,
        active: true,
        activeColor: '#ede100',
    },
    {
        id: 'stat-health',
        icon: 'icon-heart',
        hidden: false,
        color: '#cc0000',
        value: 200,
        min: 100,
        max: 200,
        active: true,
        activeColor: '#cc0000',
    },
    {
        id: 'stat-armour',
        icon: 'icon-shield2',
        hidden: false,
        color: '#0055ff',
        value: 0,
        min: 0,
        max: 100,
        active: false,
        activeColor: '#ede100',
    },
];
