export const appearanceNames = [
    'Blemishes',
    'Ageing',
    'Makeup',
    'Blush',
    'Complexion',
    'Sun Damage',
    'Lipstick',
    'Freckles',
];

export const appearanceItemNames = [
    // blemishes
    [
        'None',
        'Measles',
        'Pimples',
        'Spots',
        'Break Out',
        'Blackheads',
        'Build Up',
        'Pustules',
        'Zits',
        'Full Acne',
        'Acne',
        'Cheek Rash',
        'Face Rash',
        'Picker',
        'Puberty',
        'Eyesore',
        'Chin Rash',
        'Two Face',
        'T Zone',
        'Greasy',
        'Marked',
        'Acne Scarring',
        'Full Acne Scarring',
        'Cold Sores',
        'Impetigo',
    ],

    // ageing
    [
        'None',
        "Crow's Feet",
        'First Signs',
        'Middle Aged',
        'Worry Lines',
        'Depression',
        'Distinguished',
        'Aged',
        'Weathered',
        'Wrinkled',
        'Sagging',
        'Tough Life',
        'Vintage',
        'Retired',
        'Junkie',
        'Geriatric',
    ],
    // makeup
    [
        'None',
        'Smoky Black',
        'Bronze',
        'Soft Gray',
        'Retro Glam',
        'Natural Look',
        'Cat Eyes',
        'Chola',
        'Vamp',
        'Vinewood Glamour',
        'Bubblegum',
        'Aqua Dream',
        'Pin Up',
        'Purple Passion',
        'Smoky Cat Eye',
        'Smoldering Ruby',
        'Pop Princess',
    ],
    // blush
    ['None', 'Full', 'Angled', 'Round', 'Horizontal', 'High', 'Sweetheart', 'Eighties'],
    // complexion
    [
        'None',
        'Rosy Cheeks',
        'Stubble Rash',
        'Hot Flush',
        'Sunburn',
        'Bruised',
        'Alchoholic',
        'Patchy',
        'Totem',
        'Blood Vessels',
        'Damaged',
        'Pale',
        'Ghostly',
    ],
    // sun damage
    [
        'None',
        'Uneven',
        'Sandpaper',
        'Patchy',
        'Rough',
        'Leathery',
        'Textured',
        'Coarse',
        'Rugged',
        'Creased',
        'Cracked',
        'Gritty',
    ],
    // lipstick
    [
        'None',
        'Color Matte',
        'Color Gloss',
        'Lined Matte',
        'Lined Gloss',
        'Heavy Lined Matte',
        'Heavy Lined Gloss',
        'Lined Nude Matte',
        'Liner Nude Gloss',
        'Smudged',
        'Geisha',
    ],
    // freckles
    [
        'None',
        'Cherub',
        'All Over',
        'Irregular',
        'Dot Dash',
        'Over the Bridge',
        'Baby Doll',
        'Pixie',
        'Sun Kissed',
        'Beauty Marks',
        'Line Up',
        'Modelesque',
        'Occasional',
        'Speckled',
        'Rain Drops',
        'Double Dip',
        'One Sided',
        'Pairs',
        'Growth',
    ],
];
