export const eyeColors = [
    'Green',
    'Emerald',
    'Light Blue',
    'Ocean Blue',
    'Light Brown',
    'Dark Brown',
    'Hazel',
    'Dark Gray',
    'Light Gray',
    'Pink',
    'Yellow',
    'Purple',
    'Blackout',
    'Shades of Gray',
    'Tequila Sunrise',
    'Atomic',
    'Warp',
    'ECola',
    'Space Ranger',
    'Ying Yang',
    'Bullseye',
    'Lizard',
    'Dragon',
    'Extra Terrestrial',
    'Goat',
    'Smiley',
    'Possessed',
    'Demon',
    'Infected',
    'Alien',
    'Undead',
    'Zombie',
];

export const eyeBrows = [

    'Balanced',
    'Fashion',
    'Cleopatra',
    'Quizzical',
    'Femme',
    'Seductive',
    'Pinched',
    'Chola',
    'Triomphe',
    'Carefree',
    'Curvaceous',
    'Rodent',
    'Double Tram',
    'Thin',
    'Penciled',
    'Mother Plucker',
    'Straight and Narrow',
    'Natural',
    'Fuzzy',
    'Unkempt',
    'Caterpillar',
    'Regular',
    'Mediterranean',
    'Groomed',
    'Bushels',
    'Feathered',
    'Prickly',
    'Monobrow',
    'Winged',
    'Triple Tram',
    'Arched Tram',
    'Cutouts',
    'Fade Away',
    'Solo Tram',
    'None',
];
