export const hairList = [
    // female
    [
        { id: 0, name: 'Close Shave', collection: 'mpbeach_overlays', Overlay: 'FM_Hair_Fuzz' },
        { id: 1, name: 'Short', collection: 'multiplayer_overlays', Overlay: 'NG_F_Hair_001' },
        { id: 2, name: 'Layered Bob', collection: 'multiplayer_overlays', Overlay: 'NG_F_Hair_002' },
        { id: 3, name: 'Pigtails', collection: 'multiplayer_overlays', Overlay: 'NG_F_Hair_003' },
        { id: 4, name: 'Ponytail', collection: 'multiplayer_overlays', Overlay: 'NG_F_Hair_004' },
        { id: 5, name: 'Braided Mohawk', collection: 'multiplayer_overlays', Overlay: 'NG_F_Hair_005' },
        { id: 6, name: 'Braids', collection: 'multiplayer_overlays', Overlay: 'NG_F_Hair_006' },
        { id: 7, name: 'Bob', collection: 'multiplayer_overlays', Overlay: 'NG_F_Hair_007' },
        { id: 8, name: 'Faux Hawk', collection: 'multiplayer_overlays', Overlay: 'NG_F_Hair_008' },
        { id: 9, name: 'French Twist', collection: 'multiplayer_overlays', Overlay: 'NG_F_Hair_009' },
        { id: 10, name: 'Long Bob', collection: 'multiplayer_overlays', Overlay: 'NG_F_Hair_010' },
        { id: 11, name: 'Loose Tied', collection: 'multiplayer_overlays', Overlay: 'NG_F_Hair_011' },
        { id: 12, name: 'Pixie', collection: 'multiplayer_overlays', Overlay: 'NG_F_Hair_012' },
        { id: 13, name: 'Shaved Bangs', collection: 'multiplayer_overlays', Overlay: 'NG_F_Hair_013' },
        { id: 14, name: 'Top Knot', collection: 'multiplayer_overlays', Overlay: 'NG_M_Hair_014' },
        { id: 15, name: 'Wavy Bob', collection: 'multiplayer_overlays', Overlay: 'NG_M_Hair_015' },
        { id: 16, name: 'Messy Bun', collection: 'multiplayer_overlays', Overlay: 'NGBea_F_Hair_000' },
        { id: 17, name: 'Pin Up Girl', collection: 'multiplayer_overlays', Overlay: 'NGBea_F_Hair_001' },
        { id: 18, name: 'Tight Bun', collection: 'multiplayer_overlays', Overlay: 'NG_F_Hair_007' },
        { id: 19, name: 'Twisted Bob', collection: 'multiplayer_overlays', Overlay: 'NGBus_F_Hair_000' },
        { id: 20, name: 'Flapper Bob', collection: 'multiplayer_overlays', Overlay: 'NGBus_F_Hair_001' },
        { id: 21, name: 'Big Bangs', collection: 'multiplayer_overlays', Overlay: 'NGBea_F_Hair_001' },
        { id: 22, name: 'Braided Top Knot', collection: 'multiplayer_overlays', Overlay: 'NGHip_F_Hair_000' },
        { id: 23, name: 'Mullet', collection: 'multiplayer_overlays', Overlay: 'NGInd_F_Hair_000' },
        { id: 25, name: 'Pinched Cornrows', collection: 'mplowrider_overlays', Overlay: 'LR_F_Hair_000' },
        { id: 26, name: 'Leaf Cornrows', collection: 'mplowrider_overlays', Overlay: 'LR_F_Hair_001' },
        { id: 27, name: 'Zig Zag Cornrows', collection: 'mplowrider_overlays', Overlay: 'LR_F_Hair_002' },
        { id: 28, name: 'Pigtail Bangs', collection: 'mplowrider2_overlays', Overlay: 'LR_F_Hair_003' },
        { id: 29, name: 'Wave Braids', collection: 'mplowrider2_overlays', Overlay: 'LR_F_Hair_003' },
        { id: 30, name: 'Coil Braids', collection: 'mplowrider2_overlays', Overlay: 'LR_F_Hair_004' },
        { id: 31, name: 'Rolled Quiff', collection: 'mplowrider2_overlays', Overlay: 'LR_F_Hair_006' },
        { id: 32, name: 'Loose Swept Back', collection: 'mpbiker_overlays', Overlay: 'MP_Biker_Hair_000_F' },
        { id: 33, name: 'Undercut Swept Back', collection: 'mpbiker_overlays', Overlay: 'MP_Biker_Hair_001_F' },
        { id: 34, name: 'Undercut Swept Side', collection: 'mpbiker_overlays', Overlay: 'MP_Biker_Hair_002_F' },
        { id: 35, name: 'Spiked Mohawk', collection: 'mpbiker_overlays', Overlay: 'MP_Biker_Hair_003_F' },
        { id: 36, name: 'Bandana and Braid', collection: 'multiplayer_overlays', Overlay: 'NG_F_Hair_003' },
        { id: 37, name: 'Layered Mod', collection: 'mpbiker_overlays', Overlay: 'MP_Biker_Hair_006_F' },
        { id: 38, name: 'Skinbyrd', collection: 'mpbiker_overlays', Overlay: 'MP_Biker_Hair_004_F' },
        { id: 76, name: 'Neat Bun', collection: 'mpgunrunning_overlays', Overlay: 'MP_Gunrunning_Hair_F_000_F' },
        { id: 77, name: 'Short Bob', collection: 'mpgunrunning_overlays', Overlay: 'MP_Gunrunning_Hair_F_001_F' },
    ],
    // male
    [
        { id: 0, name: 'Close Shave', collection: 'mpbeach_overlays', Overlay: 'FM_Hair_Fuzz' },
        { id: 1, name: 'Buzzcut', collection: 'multiplayer_overlays', Overlay: 'NG_M_Hair_001' },
        { id: 2, name: 'Faux Hawk', collection: 'multiplayer_overlays', Overlay: 'NG_M_Hair_002' },
        { id: 3, name: 'Hipster', collection: 'multiplayer_overlays', Overlay: 'NG_M_Hair_003' },
        { id: 4, name: 'Side Parting', collection: 'multiplayer_overlays', Overlay: 'NG_M_Hair_004' },
        { id: 5, name: 'Shorter Cut', collection: 'multiplayer_overlays', Overlay: 'NG_M_Hair_005' },
        { id: 6, name: 'Biker', collection: 'multiplayer_overlays', Overlay: 'NG_M_Hair_006' },
        { id: 7, name: 'Ponytail', collection: 'multiplayer_overlays', Overlay: 'NG_M_Hair_007' },
        { id: 8, name: 'Cornrows', collection: 'multiplayer_overlays', Overlay: 'NG_M_Hair_008' },
        { id: 9, name: 'Slicked', collection: 'multiplayer_overlays', Overlay: 'NG_M_Hair_009' },
        { id: 10, name: 'Short Brushed', collection: 'multiplayer_overlays', Overlay: 'NG_M_Hair_013' },
        { id: 11, name: 'Spikey', collection: 'multiplayer_overlays', Overlay: 'NG_M_Hair_002' },
        { id: 12, name: 'Caesar', collection: 'multiplayer_overlays', Overlay: 'NG_M_Hair_011' },
        { id: 13, name: 'Chopped', collection: 'multiplayer_overlays', Overlay: 'NG_M_Hair_012' },
        { id: 14, name: 'Dreads', collection: 'multiplayer_overlays', Overlay: 'NG_M_Hair_014' },
        { id: 15, name: 'Long Hair', collection: 'multiplayer_overlays', Overlay: 'NG_M_Hair_015' },
        { id: 16, name: 'Shaggy Curls', collection: 'multiplayer_overlays', Overlay: 'NGBea_M_Hair_000' },
        { id: 17, name: 'Surfer Dude', collection: 'multiplayer_overlays', Overlay: 'NGBea_M_Hair_001' },
        { id: 18, name: 'Short Side Part', collection: 'multiplayer_overlays', Overlay: 'NGBus_M_Hair_000' },
        { id: 19, name: 'High Slicked Sides', collection: 'multiplayer_overlays', Overlay: 'NGBus_M_Hair_001' },
        { id: 20, name: 'Long Slicked', collection: 'multiplayer_overlays', Overlay: 'NGHip_M_Hair_000' },
        { id: 21, name: 'Hipster Youth', collection: 'multiplayer_overlays', Overlay: 'NGHip_M_Hair_001' },
        { id: 22, name: 'Mullet', collection: 'multiplayer_overlays', Overlay: 'NGInd_M_Hair_000' },
        { id: 24, name: 'Classic Cornrows', collection: 'mplowrider_overlays', Overlay: 'LR_M_Hair_000' },
        { id: 25, name: 'Palm Cornrows', collection: 'mplowrider_overlays', Overlay: 'LR_M_Hair_001' },
        { id: 26, name: 'Lightning Cornrows', collection: 'mplowrider_overlays', Overlay: 'LR_M_Hair_002' },
        { id: 27, name: 'Whipped Cornrows', collection: 'mplowrider_overlays', Overlay: 'LR_M_Hair_003' },
        { id: 28, name: 'Zig Zag Cornrows', collection: 'mplowrider2_overlays', Overlay: 'LR_M_Hair_004' },
        { id: 29, name: 'Snail Cornrows', collection: 'mplowrider2_overlays', Overlay: 'LR_M_Hair_005' },
        { id: 30, name: 'Hightop', collection: 'mplowrider2_overlays', Overlay: 'LR_M_Hair_006' },
        { id: 31, name: 'Loose Swept Back', collection: 'mpbiker_overlays', Overlay: 'MP_Biker_Hair_000_M' },
        { id: 32, name: 'Undercut Swept Back', collection: 'mpbiker_overlays', Overlay: 'MP_Biker_Hair_001_M' },
        { id: 33, name: 'Undercut Swept Side', collection: 'mpbiker_overlays', Overlay: 'MP_Biker_Hair_002_M' },
        { id: 34, name: 'Spiked Mohawk', collection: 'mpbiker_overlays', Overlay: 'MP_Biker_Hair_003_M' },
        { id: 35, name: 'Mod', collection: 'mpbiker_overlays', Overlay: 'MP_Biker_Hair_004_M' },
        { id: 36, name: 'Layered Mod', collection: 'mpbiker_overlays', Overlay: 'MP_Biker_Hair_005_M' },
        { id: 72, name: 'Flattop' },
        { id: 73, name: 'Military Buzzcut' },
    ],
];

export const facialHairNames = [
    'Light Stubble',
    'Balbo',
    'Circle Beard',
    'Goatee',
    'Chin',
    'Chin Fuzz',
    'Pencil Chin Strap',
    'Scruffy',
    'Musketeer',
    'Mustache',
    'Trimmed Beard',
    'Stubble',
    'Thin Circle Beard',
    'Horseshoe',
    "Pencil and 'Chops",
    'Chin Strap Beard',
    'Balbo and Sideburns',
    'Mutton Chops',
    'Scruffy Beard',
    'Curly',
    'Curly & Deep Stranger',
    'Handlebar',
    'Faustic',
    'Otto & Patch',
    'Otto & Full Stranger',
    'Light Franz',
    'The Hampstead',
    'The Ambrose',
    'Lincoln Curtain',
    'None',
];

export const chestHairNames = [
    'Natural',
    'The Strip',
    'The Tree',
    'Hairy',
    'Grisly',
    'Ape',
    'Groomed Ape',
    'Bikini',
    'Lightning Bolt',
    'Reverse Lightning',
    'Love Heart',
    'Chestache',
    'Happy Face',
    'Skull',
    'Snail Trail',
    'Slug and Nips',
    'Hairy Arms',
    'None',
];
