import { useTranslate } from '@Shared/translate.js';
const { setBulk } = useTranslate();

setBulk({
    en: {
        'character.creator.title': 'Character creator',
        'character.creator.save': 'Save',
        'character.creator.back': 'Back',
        'character.creator.use': 'Use',
        'character.creator.to.navigate': 'to navigate quicker',
        'character.creator.dna': 'Dna',
        'character.creator.sex': 'Sex',
        'character.creator.male': 'Male',
        'character.creator.female': 'Female',
        'character.creator.resemblance': 'Resemblance',
        'character.creator.skintone': 'Skintone',
        'character.creator.random': 'Random',
        'character.creator.reset': 'Reset',
        'character.creator.opacity': 'Opacity',
        'character.creator.hair': 'Hair',
        'character.creator.facial.hair': 'Facial hair',
        'character.creator.chest.hair': 'Body hair',
        'character.creator.hair.color': 'Hair color',
        'character.creator.highlight.color': 'Highlight color',
        'character.creator.facial.color': 'Facial hair color',
        'character.creator.chest.color': 'Body hair color',
        'character.creator.eyes': 'Eyes',
        'character.creator.eyes.color': 'Eyes color',
        'character.creator.eyebrows': 'Eyebrows',
        'character.creator.eyebrows.color': 'Eyebrows color',
        'character.creator.features': 'Features',
        'character.creator.appearance': 'Appearance',
        'character.creator.top': 'Top',
        'character.creator.undershirt': 'Undershirt',
        'character.creator.legs': 'Legs',
        'character.creator.shoes': 'Shoes',
        'character.creator.hat': 'Head',
        'character.creator.accesories': 'Accesories',

        'character.creator.first.name': 'First name',
        'character.creator.last.name': 'Last name',
        'character.creator.age': 'Age',

        'character.creator.verify.name': 'Verify name',
        'character.creator.finish': 'Finish',
        'character.creator.name.taken': 'Name is already taken',
        'character.creator.name.error': 'Invalid name format',
        'character.creator.day.error': 'Age must be form 18 to 99',

        'character.creator.rotate': 'Rotate',
        'character.creator.updown': 'Up / Down',
        'character.creator.zoom': 'Zoom in / out',
    },
    lt: {
        'character.creator.title': 'Veikėjo kūrimas',
        'character.creator.save': 'Saugoti',
        'character.creator.back': 'Atgal',
        'character.creator.use': 'Naudokite',
        'character.creator.to.navigate': 'greitam pasirinkimui',
        'character.creator.dna': 'Dna',
        'character.creator.sex': 'Lytis',
        'character.creator.male': 'Vyras',
        'character.creator.female': 'Moteris',
        'character.creator.resemblance': 'Panašumas',
        'character.creator.skintone': 'Odos spavla',
        'character.creator.random': 'Random',
        'character.creator.reset': 'Atstatyti',
        'character.creator.opacity': 'Matomumas',
        'character.creator.hair': 'Plaukai',
        'character.creator.facial.hair': 'Barzda',
        'character.creator.chest.hair': 'Kūno plaukai',
        'character.creator.hair.color': 'Plaukų spalva',
        'character.creator.highlight.color': 'Sruogelių spalva',
        'character.creator.facial.color': 'Barzdos spalva',
        'character.creator.chest.color': 'Kūno plaukų spalva',
        'character.creator.eyes': 'Akys',
        'character.creator.eyes.color': 'Akių spalva',
        'character.creator.eyebrows': 'Antakiai',
        'character.creator.eyebrows.color': 'Antakių spalva',
        'character.creator.features': 'Bruožai',
        'character.creator.appearance': 'Išvaizda',
        'character.creator.top': 'Viršus',
        'character.creator.undershirt': 'Marškiniai',
        'character.creator.legs': 'Kojos',
        'character.creator.shoes': 'Batai',
        'character.creator.hat': 'Galva',
        'character.creator.accesories': 'Aksesuarai',

        'character.creator.first.name': 'Vardas',
        'character.creator.last.name': 'Pavardė',
        'character.creator.age': 'Amžius',

        'character.creator.verify.name': 'Patvirtinti vardą',
        'character.creator.finish': 'Baigti',
        'character.creator.name.taken': 'Vardas jau užimtas',
        'character.creator.name.error': 'Netinkamas vardo formatas',
        'character.creator.day.error': 'Amžius privalo būti tarp 18 ir 99',

        'character.creator.rotate': 'Pasukti',
        'character.creator.updown': 'Aukštyn / Žemyn',
        'character.creator.zoom': 'Pritraukti arčiau / toliau',
    },
});
